version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: musaushev/translator:1.0.1
  graphql:
    build:
      context: ./
      dockerfile: ./Graphql.DockerFile
    image: musaushev/graphql:1.0.1