swagger: '2.0'
info:
  title: translator - admin panel
  version: 1.0.0
host: '68.183.7.178:1855'
schemes:
  - http
basePath: /api/admin
produces:
  - application/json
paths:
  /login:
    post:
      tags:
      - Login
      summary: login & password
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            login:
              type: string
            password:
              type: string
          example:
            login: login
            password: password
      responses:
        200:
          description: ok
  /upload:
    post:
      tags:
       - Upload
      summary: Upload files
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: file
        type: file
      responses:
        200:
          description: ok