swagger: '2.0'
info:
  title: translator
  version: 1.0.0
host: '68.183.7.178:1854'
schemes:
  - http
basePath: /api
produces:
  - application/json
paths:
  /users/login:
    post:
      tags:
      - User
      summary: Send code for register/login
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            phone:
              type: string
      responses:
        200:
          description: ok
  /users/confirm:
    post:
      tags:
      - User
      summary: Confirm code for authorization
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            _id:
              type: string
            code:
              type: string
      responses:
        200:
          description: if param firstIn true, then redirect user on update info about him
  /users/info:
    get:
      tags:
      - User
      summary: Get info about me
      responses:
        200:
          description: ok
    put:
      tags:
      - User
      summary: Update info about me
      parameters:
      - in: body
        name: body
        schema:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            middleName:
              type: string
            email:
              type: string
      responses:
        200:
          description: ok
  /tasks/{level}:
    get:
      tags:
        - Task
      summary: Get random not completed user task
      parameters:
        - in: path
          name: level
          type: string
          required: true
      responses:
        200:
          description: ok
  /tasks/{id}/answer:
    post:
      tags:
        - Task
      summary: Check task answer
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: body
          schema:
            type: object
            properties:
              answer:
                type: string
      responses:
        200:
          description: ok
